### ISSUE TITLE
ESP32RestSerialAPI command not compatible with each other

### ISSUE THREAD

**Issue by ranranking** [openUC2/UC2-REST#6]
Hey, in the **test_ESP32RestSerialAPI.py** the `move_stepper` command variable is not compatible `def`. In  `def move_stepper()`there is no `axis` para rather `steps` with all 3 directions. Please fix it

**Comment by beniroquai** [comment]
Hopefully fixed for now. We need a better way of dealing with this package vs. package inside Imswitch. Perhaps a Pip package?
