### ISSUE TITLE
Failed to load camera model

### ISSUE THREAD

**Issue by Farghal1** [openUC2/UC2-REST#78]
Hello,

I'm trying to use imswitch with uc2. After I selected the suitable config file, LEDs and motors are working fine. The issue is with the camera it's not loaded and the mock model is used. I tried to change the cameraListIndex from 0:2 in the config file but nothing seems to happen and always the mock model is loaded.

Also, the camera is connected and I tested its functionality using Vimba x viewer.

![mocker loaded](https://github.com/openUC2/UC2-REST/assets/83556140/539c3691-6594-4afd-b858-de34d2d02cd6)

**Comment by beniroquai** [comment]
which camera are you trying to launch on which computer? Can you try the pymba examples successfully? https://github.com/morefigs/pymba
